export const LOST = 'lost'
export const CHASE = 'chase'
export const NO_OFFENCE = 'no-offence'
export const INVESTIGATE = 'investigate'
export const GUESS_SEARCH = 'guess-search'
export const MOVE_TO_POSITION = 'move-to-position'
export const GO_FOR_RANGED = 'go-for-ranged'