export const rooms = `[{"id":1,"width":400,"height":600,"label":"Dormitory","brightness":10,"progress2Active":["1000"],"progress2Deactive":[],"background":"lightgrey"},{"id":2,"width":700,"height":450,"label":"Bunker A","brightness":8,"progress2Active":["2000"],"progress2Deactive":[],"background":"lightgrey"},{"id":3,"width":500,"height":1000,"label":"Bunker B","brightness":8,"progress2Active":["3000"],"progress2Deactive":[],"background":"lightgrey"}]`

export const walls = `{"1":[{"width":50,"height":25,"left":75,"right":null,"top":75,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":75,"right":null,"top":175,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":75,"right":null,"top":275,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":75,"right":null,"top":375,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":null,"right":75,"top":75,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":null,"right":75,"top":175,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":null,"right":75,"top":275,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":null,"right":75,"top":375,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":75,"right":null,"top":475,"bottom":null,"background":"lightslategrey","side":false},{"width":50,"height":25,"left":null,"right":75,"top":475,"bottom":null,"background":"lightslategrey","side":false}],"2":[{"width":400,"height":50,"left":150,"right":null,"top":200,"bottom":null,"background":"lightslategrey","side":false}],"3":[]}`

export const loaders = `{"1":[{"className":2,"width":100,"height":5,"left":150,"top":-26,"right":null,"bottom":null,"door":{"name":"door","heading":"Dorm door","popup":"A sturdy door","key":"dorm","renderProgress":"1009","progress2Active":[],"killAll":null,"type":1,"code":null,"value":""}}],"2":[{"className":1,"width":100,"height":5,"left":300,"top":null,"right":null,"bottom":-26,"door":null},{"className":3,"width":100,"height":5,"left":300,"top":-26,"right":null,"bottom":null,"door":{"name":"door","heading":"Bunker B","popup":"Door made of iron","key":null,"renderProgress":"2003","progress2Active":[],"killAll":null,"type":2,"code":null,"value":""}}],"3":[{"className":2,"width":100,"height":5,"left":200,"top":null,"right":null,"bottom":-26,"door":null}]}`

export const enemies = `{"1":[],"2":[{"type":"torturer","components":4,"waypoint":{"points":[{"x":150,"y":150},{"x":550,"y":150}]},"health":141,"damage":12,"maxSpeed":3.6465710199547345,"virus":"green","vision":600,"acceleration":1.5,"renderProgress":"2000","progress2Active":[],"progress2Deactive":[],"killAll":null,"x":150,"y":150,"level":1,"knock":100,"loot":{},"difficulties":["mild","middle","survival"],"damagedCounter":0}],"3":[]}`

export const interactables = `{"1":[{"width":15,"left":100,"top":125,"name":"note","heading":"Prisoner's note","popup":"Pick up","solid":false,"amount":1,"space":1,"description":"Note explaining what a prisoner experienced in this cell","price":0,"renderProgress":"1002","killAll":null,"progress2Active":["1003"],"progress2Deactive":["1004"],"onexamine":["1005"],"difficulties":["mild","middle","survival"],"data":"I don't understand. All I remember was my ordinary life. And now, I'm stuck here, alone... I don't even know if I'm kidnapped or captured by law. Even then I would've contacted someone by now. It's been 2 days since I'm here. The hunger is torturing me. Seems like I'm not completely imprisoned, because the door's key is just here. But I'm too afraid to leave, I can hear a predator breathing past the door every now and then. I guess I'd better make a move, or else I will starve to death.","code":null,"examined":false},{"width":10,"left":300,"top":525,"name":"key-1","heading":"Dorm key","popup":"Pick up","solid":false,"amount":1,"space":1,"description":"Must be the same key that the prisoner was talking about","price":0,"renderProgress":"1006","killAll":null,"progress2Active":["1007"],"progress2Deactive":[],"onexamine":[],"difficulties":["mild","middle","survival"],"unlocks":"dorm"}],"2":[{"width":30,"left":650,"top":150,"name":"lever","heading":"lever","popup":"Toggle","solid":true,"amount":0,"space":0,"description":null,"price":0,"renderProgress":"2000","killAll":null,"progress2Active":["2003"],"progress2Deactive":[],"onexamine":[],"difficulties":["mild","middle","survival"]}],"3":[]}`

export const popups = `[{"message":"<span>W</span> <span>A</span> <span>S</span> <span>D</span> Move","renderProgress":"1001","progress2Active":["1002"]},{"message":"<span>Tab</span> Open inventory.","renderProgress":"1003","progress2Active":["1004"]},{"message":"You can manage your items in your inventory. Like replacing items, examine stats, read notes, use consumables, equip equipables or even drop the unnecessary stuff. Feel free to try and error with this environment. ","renderProgress":"1004","progress2Active":[]},{"message":"Open inventory and use the key","renderProgress":"1008","progress2Active":[]},{"message":"Avoid the monster's detection. The enemies have a usual path for investigation. Try to figure out there pattern and stay out of their sight. Being visible by enemies or making noise can catch their attention to your presence.","renderProgress":"2002","progress2Active":[]},{"message":"You are detected by an enemy. The enemies will chase you until you lose them. You can lose enemies by staying out of their sight, like hiding behind walls.","renderProgress":"2005","progress2Active":["2006"]},{"message":"You can use <span>Space</span> to run away quicker. However, this will make noise and the monsters will follow the noise source.","renderProgress":"2006","progress2Active":[]}]`

export const dialogues = `[{"message":"Where the hell am I?","source":"main","renderProgress":"1000","progress2Active":["1001"],"duration":3000},{"message":"What the... I gotta find that key.","source":"main","renderProgress":"1005","progress2Active":["1006"],"duration":3000},{"message":"There it is.","source":"main","renderProgress":"1007","progress2Active":[],"duration":3000},{"message":"What's that noise?","source":"main","renderProgress":"2000","progress2Active":["2001"],"duration":3000},{"message":"Whatever it is I should not catch its attention.","source":"main","renderProgress":"2001","progress2Active":["2002"],"duration":3000}]`

export const shopItems = `[]`
